version: '2'

services:
  geth-dev:
    build: geth-dev
    ports:
      - 8545:8545
  fund-signer:
    image: ethereum/client-go:release-1.10
    entrypoint: 'geth --exec "eth.sendTransaction({from: eth.accounts[0], to: \"0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266\", value: web3.toWei(10000, \"ether\")})" attach http://geth-dev:8545'
    depends_on:
      geth-dev:
        condition: service_started